/* Generated by Yosys 0.43 (git sha1 ead4718e5, clang++ 15.0.0 -fPIC -Os) */

(* top =  1  *)
(* generator = "Amaranth" *)
(* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:39" *)
module top(in_down, in_left, in_right, run_rst, run_enable, program_up, program_down, program_left, program_right, program_rst, program_enable, clk, rst, out_up, out_down, out_left, out_right, in_up);
  wire _000_;
  wire _001_;
  wire _002_;
  wire [15:0] _003_;
  wire _004_;
  wire [15:0] _005_;
  wire [15:0] _006_;
  wire [15:0] _007_;
  wire _008_;
  wire _009_;
  (* force_downto = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _010_;
  (* force_downto = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [4:0] _011_;
  (* force_downto = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _012_;
  (* force_downto = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [4:0] _013_;
  (* force_downto = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _014_;
  (* force_downto = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [4:0] _015_;
  (* force_downto = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _016_;
  (* force_downto = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [4:0] _017_;
  (* force_downto = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _018_;
  (* force_downto = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _019_;
  (* src = "hw.v:7.7-7.51" *)
  wire \$auto$verilog_backend.cc:2352:dump_module$1 ;
  (* src = "/Users/stefan/miniforge3/envs/ml-env/lib/python3.11/site-packages/amaranth/hdl/_ir.py:283" *)
  input clk;
  wire clk;
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:45" *)
  wire f_down;
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:46" *)
  wire f_left;
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:47" *)
  wire f_right;
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:44" *)
  wire f_up;
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:42" *)
  wire [3:0] in_concat;
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:18" *)
  input in_down;
  wire in_down;
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:19" *)
  input in_left;
  wire in_left;
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:20" *)
  input in_right;
  wire in_right;
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:17" *)
  input in_up;
  wire in_up;
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:23" *)
  output out_down;
  wire out_down;
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:24" *)
  output out_left;
  wire out_left;
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:41" *)
  wire [3:0] out_reg;
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:25" *)
  output out_right;
  wire out_right;
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:22" *)
  output out_up;
  wire out_up;
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:31" *)
  input [15:0] program_down;
  wire [15:0] program_down;
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:50" *)
  wire [15:0] program_down_reg;
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:36" *)
  input program_enable;
  wire program_enable;
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:32" *)
  input [15:0] program_left;
  wire [15:0] program_left;
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:51" *)
  wire [15:0] program_left_reg;
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:33" *)
  input [15:0] program_right;
  wire [15:0] program_right;
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:52" *)
  wire [15:0] program_right_reg;
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:35" *)
  input program_rst;
  wire program_rst;
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:30" *)
  input [15:0] program_up;
  wire [15:0] program_up;
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:49" *)
  wire [15:0] program_up_reg;
  (* src = "/Users/stefan/miniforge3/envs/ml-env/lib/python3.11/site-packages/amaranth/hdl/_ir.py:283" *)
  input rst;
  wire rst;
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:28" *)
  input run_enable;
  wire run_enable;
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:27" *)
  input run_rst;
  wire run_rst;
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hf7d5b391e6c4a280)
  ) _020_ (
    .I0(in_concat[1]),
    .I1(in_concat[0]),
    .I2(program_right_reg[3]),
    .I3(program_right_reg[2]),
    .I4(program_right_reg[1]),
    .I5(program_right_reg[0]),
    .O(_013_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hf7d5b391e6c4a280)
  ) _021_ (
    .I0(in_concat[1]),
    .I1(in_concat[0]),
    .I2(program_right_reg[7]),
    .I3(program_right_reg[6]),
    .I4(program_right_reg[5]),
    .I5(program_right_reg[4]),
    .O(_013_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hf7d5b391e6c4a280)
  ) _022_ (
    .I0(in_concat[2]),
    .I1(in_concat[0]),
    .I2(program_right_reg[15]),
    .I3(program_right_reg[14]),
    .I4(program_right_reg[11]),
    .I5(program_right_reg[10]),
    .O(_012_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hf7d5b391e6c4a280)
  ) _023_ (
    .I0(in_concat[2]),
    .I1(in_concat[0]),
    .I2(program_right_reg[13]),
    .I3(program_right_reg[12]),
    .I4(program_right_reg[9]),
    .I5(program_right_reg[8]),
    .O(_012_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'he4)
  ) _024_ (
    .I0(in_concat[1]),
    .I1(_012_[1]),
    .I2(_012_[2]),
    .O(_013_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hf7d5b391e6c4a280)
  ) _025_ (
    .I0(in_concat[1]),
    .I1(in_concat[0]),
    .I2(program_down_reg[3]),
    .I3(program_down_reg[2]),
    .I4(program_down_reg[1]),
    .I5(program_down_reg[0]),
    .O(_015_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hf7d5b391e6c4a280)
  ) _026_ (
    .I0(in_concat[1]),
    .I1(in_concat[0]),
    .I2(program_down_reg[7]),
    .I3(program_down_reg[6]),
    .I4(program_down_reg[5]),
    .I5(program_down_reg[4]),
    .O(_015_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hf7d5b391e6c4a280)
  ) _027_ (
    .I0(in_concat[2]),
    .I1(in_concat[0]),
    .I2(program_down_reg[15]),
    .I3(program_down_reg[14]),
    .I4(program_down_reg[11]),
    .I5(program_down_reg[10]),
    .O(_014_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hf7d5b391e6c4a280)
  ) _028_ (
    .I0(in_concat[2]),
    .I1(in_concat[0]),
    .I2(program_down_reg[13]),
    .I3(program_down_reg[12]),
    .I4(program_down_reg[9]),
    .I5(program_down_reg[8]),
    .O(_014_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'he4)
  ) _029_ (
    .I0(in_concat[1]),
    .I1(_014_[1]),
    .I2(_014_[2]),
    .O(_015_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hf7d5b391e6c4a280)
  ) _030_ (
    .I0(in_concat[1]),
    .I1(in_concat[0]),
    .I2(program_up_reg[3]),
    .I3(program_up_reg[2]),
    .I4(program_up_reg[1]),
    .I5(program_up_reg[0]),
    .O(_017_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hf7d5b391e6c4a280)
  ) _031_ (
    .I0(in_concat[1]),
    .I1(in_concat[0]),
    .I2(program_up_reg[7]),
    .I3(program_up_reg[6]),
    .I4(program_up_reg[5]),
    .I5(program_up_reg[4]),
    .O(_017_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hf7d5b391e6c4a280)
  ) _032_ (
    .I0(in_concat[2]),
    .I1(in_concat[0]),
    .I2(program_up_reg[15]),
    .I3(program_up_reg[14]),
    .I4(program_up_reg[11]),
    .I5(program_up_reg[10]),
    .O(_016_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hf7d5b391e6c4a280)
  ) _033_ (
    .I0(in_concat[2]),
    .I1(in_concat[0]),
    .I2(program_up_reg[13]),
    .I3(program_up_reg[12]),
    .I4(program_up_reg[9]),
    .I5(program_up_reg[8]),
    .O(_016_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'he4)
  ) _034_ (
    .I0(in_concat[1]),
    .I1(_016_[1]),
    .I2(_016_[2]),
    .O(_017_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hf7d5b391e6c4a280)
  ) _035_ (
    .I0(in_concat[1]),
    .I1(in_concat[0]),
    .I2(program_left_reg[3]),
    .I3(program_left_reg[2]),
    .I4(program_left_reg[1]),
    .I5(program_left_reg[0]),
    .O(_011_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hf7d5b391e6c4a280)
  ) _036_ (
    .I0(in_concat[1]),
    .I1(in_concat[0]),
    .I2(program_left_reg[7]),
    .I3(program_left_reg[6]),
    .I4(program_left_reg[5]),
    .I5(program_left_reg[4]),
    .O(_011_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hf7d5b391e6c4a280)
  ) _037_ (
    .I0(in_concat[2]),
    .I1(in_concat[0]),
    .I2(program_left_reg[15]),
    .I3(program_left_reg[14]),
    .I4(program_left_reg[11]),
    .I5(program_left_reg[10]),
    .O(_010_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hf7d5b391e6c4a280)
  ) _038_ (
    .I0(in_concat[2]),
    .I1(in_concat[0]),
    .I2(program_left_reg[13]),
    .I3(program_left_reg[12]),
    .I4(program_left_reg[9]),
    .I5(program_left_reg[8]),
    .O(_010_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'he4)
  ) _039_ (
    .I0(in_concat[1]),
    .I1(_010_[1]),
    .I2(_010_[2]),
    .O(_011_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4226437440)
  ) _040_ (
    .I0(in_concat[3]),
    .I1(in_concat[2]),
    .I2(_015_[2]),
    .I3(_015_[3]),
    .I4(_015_[4]),
    .O(f_down)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4226437440)
  ) _041_ (
    .I0(in_concat[3]),
    .I1(in_concat[2]),
    .I2(_011_[2]),
    .I3(_011_[3]),
    .I4(_011_[4]),
    .O(f_left)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4226437440)
  ) _042_ (
    .I0(in_concat[3]),
    .I1(in_concat[2]),
    .I2(_013_[2]),
    .I3(_013_[3]),
    .I4(_013_[4]),
    .O(f_right)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4226437440)
  ) _043_ (
    .I0(in_concat[3]),
    .I1(in_concat[2]),
    .I2(_017_[2]),
    .I3(_017_[3]),
    .I4(_017_[4]),
    .O(f_up)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'he)
  ) _044_ (
    .I0(_018_[0]),
    .I1(_018_[1]),
    .O(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'he)
  ) _045_ (
    .I0(_019_[0]),
    .I1(_018_[0]),
    .O(_000_)
  );
  BUFG _046_ (
    .I(_009_),
    .O(_002_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:41|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _047_ (
    .C(_002_),
    .CE(_008_),
    .D(f_up),
    .Q(out_reg[0]),
    .R(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:41|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _048_ (
    .C(_002_),
    .CE(_008_),
    .D(f_down),
    .Q(out_reg[1]),
    .R(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:41|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _049_ (
    .C(_002_),
    .CE(_008_),
    .D(f_left),
    .Q(out_reg[2]),
    .R(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:41|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _050_ (
    .C(_002_),
    .CE(_008_),
    .D(f_right),
    .Q(out_reg[3]),
    .R(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:52|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _051_ (
    .C(_002_),
    .CE(_004_),
    .D(_006_[0]),
    .Q(program_right_reg[0]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:52|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _052_ (
    .C(_002_),
    .CE(_004_),
    .D(_006_[1]),
    .Q(program_right_reg[1]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:52|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _053_ (
    .C(_002_),
    .CE(_004_),
    .D(_006_[2]),
    .Q(program_right_reg[2]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:52|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _054_ (
    .C(_002_),
    .CE(_004_),
    .D(_006_[3]),
    .Q(program_right_reg[3]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:52|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _055_ (
    .C(_002_),
    .CE(_004_),
    .D(_006_[4]),
    .Q(program_right_reg[4]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:52|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _056_ (
    .C(_002_),
    .CE(_004_),
    .D(_006_[5]),
    .Q(program_right_reg[5]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:52|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _057_ (
    .C(_002_),
    .CE(_004_),
    .D(_006_[6]),
    .Q(program_right_reg[6]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:52|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _058_ (
    .C(_002_),
    .CE(_004_),
    .D(_006_[7]),
    .Q(program_right_reg[7]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:52|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _059_ (
    .C(_002_),
    .CE(_004_),
    .D(_006_[8]),
    .Q(program_right_reg[8]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:52|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _060_ (
    .C(_002_),
    .CE(_004_),
    .D(_006_[9]),
    .Q(program_right_reg[9]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:52|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _061_ (
    .C(_002_),
    .CE(_004_),
    .D(_006_[10]),
    .Q(program_right_reg[10]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:52|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _062_ (
    .C(_002_),
    .CE(_004_),
    .D(_006_[11]),
    .Q(program_right_reg[11]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:52|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _063_ (
    .C(_002_),
    .CE(_004_),
    .D(_006_[12]),
    .Q(program_right_reg[12]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:52|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _064_ (
    .C(_002_),
    .CE(_004_),
    .D(_006_[13]),
    .Q(program_right_reg[13]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:52|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _065_ (
    .C(_002_),
    .CE(_004_),
    .D(_006_[14]),
    .Q(program_right_reg[14]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:52|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _066_ (
    .C(_002_),
    .CE(_004_),
    .D(_006_[15]),
    .Q(program_right_reg[15]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:51|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _067_ (
    .C(_002_),
    .CE(_004_),
    .D(_005_[0]),
    .Q(program_left_reg[0]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:51|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _068_ (
    .C(_002_),
    .CE(_004_),
    .D(_005_[1]),
    .Q(program_left_reg[1]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:51|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _069_ (
    .C(_002_),
    .CE(_004_),
    .D(_005_[2]),
    .Q(program_left_reg[2]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:51|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _070_ (
    .C(_002_),
    .CE(_004_),
    .D(_005_[3]),
    .Q(program_left_reg[3]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:51|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _071_ (
    .C(_002_),
    .CE(_004_),
    .D(_005_[4]),
    .Q(program_left_reg[4]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:51|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _072_ (
    .C(_002_),
    .CE(_004_),
    .D(_005_[5]),
    .Q(program_left_reg[5]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:51|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _073_ (
    .C(_002_),
    .CE(_004_),
    .D(_005_[6]),
    .Q(program_left_reg[6]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:51|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _074_ (
    .C(_002_),
    .CE(_004_),
    .D(_005_[7]),
    .Q(program_left_reg[7]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:51|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _075_ (
    .C(_002_),
    .CE(_004_),
    .D(_005_[8]),
    .Q(program_left_reg[8]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:51|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _076_ (
    .C(_002_),
    .CE(_004_),
    .D(_005_[9]),
    .Q(program_left_reg[9]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:51|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _077_ (
    .C(_002_),
    .CE(_004_),
    .D(_005_[10]),
    .Q(program_left_reg[10]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:51|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _078_ (
    .C(_002_),
    .CE(_004_),
    .D(_005_[11]),
    .Q(program_left_reg[11]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:51|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _079_ (
    .C(_002_),
    .CE(_004_),
    .D(_005_[12]),
    .Q(program_left_reg[12]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:51|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _080_ (
    .C(_002_),
    .CE(_004_),
    .D(_005_[13]),
    .Q(program_left_reg[13]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:51|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _081_ (
    .C(_002_),
    .CE(_004_),
    .D(_005_[14]),
    .Q(program_left_reg[14]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:51|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _082_ (
    .C(_002_),
    .CE(_004_),
    .D(_005_[15]),
    .Q(program_left_reg[15]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:50|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _083_ (
    .C(_002_),
    .CE(_004_),
    .D(_003_[0]),
    .Q(program_down_reg[0]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:50|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _084_ (
    .C(_002_),
    .CE(_004_),
    .D(_003_[1]),
    .Q(program_down_reg[1]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:50|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _085_ (
    .C(_002_),
    .CE(_004_),
    .D(_003_[2]),
    .Q(program_down_reg[2]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:50|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _086_ (
    .C(_002_),
    .CE(_004_),
    .D(_003_[3]),
    .Q(program_down_reg[3]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:50|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _087_ (
    .C(_002_),
    .CE(_004_),
    .D(_003_[4]),
    .Q(program_down_reg[4]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:50|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _088_ (
    .C(_002_),
    .CE(_004_),
    .D(_003_[5]),
    .Q(program_down_reg[5]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:50|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _089_ (
    .C(_002_),
    .CE(_004_),
    .D(_003_[6]),
    .Q(program_down_reg[6]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:50|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _090_ (
    .C(_002_),
    .CE(_004_),
    .D(_003_[7]),
    .Q(program_down_reg[7]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:50|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _091_ (
    .C(_002_),
    .CE(_004_),
    .D(_003_[8]),
    .Q(program_down_reg[8]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:50|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _092_ (
    .C(_002_),
    .CE(_004_),
    .D(_003_[9]),
    .Q(program_down_reg[9]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:50|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _093_ (
    .C(_002_),
    .CE(_004_),
    .D(_003_[10]),
    .Q(program_down_reg[10]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:50|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _094_ (
    .C(_002_),
    .CE(_004_),
    .D(_003_[11]),
    .Q(program_down_reg[11]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:50|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _095_ (
    .C(_002_),
    .CE(_004_),
    .D(_003_[12]),
    .Q(program_down_reg[12]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:50|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _096_ (
    .C(_002_),
    .CE(_004_),
    .D(_003_[13]),
    .Q(program_down_reg[13]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:50|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _097_ (
    .C(_002_),
    .CE(_004_),
    .D(_003_[14]),
    .Q(program_down_reg[14]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:50|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _098_ (
    .C(_002_),
    .CE(_004_),
    .D(_003_[15]),
    .Q(program_down_reg[15]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:49|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _099_ (
    .C(_002_),
    .CE(_004_),
    .D(_007_[0]),
    .Q(program_up_reg[0]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:49|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _100_ (
    .C(_002_),
    .CE(_004_),
    .D(_007_[1]),
    .Q(program_up_reg[1]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:49|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _101_ (
    .C(_002_),
    .CE(_004_),
    .D(_007_[2]),
    .Q(program_up_reg[2]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:49|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _102_ (
    .C(_002_),
    .CE(_004_),
    .D(_007_[3]),
    .Q(program_up_reg[3]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:49|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _103_ (
    .C(_002_),
    .CE(_004_),
    .D(_007_[4]),
    .Q(program_up_reg[4]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:49|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _104_ (
    .C(_002_),
    .CE(_004_),
    .D(_007_[5]),
    .Q(program_up_reg[5]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:49|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _105_ (
    .C(_002_),
    .CE(_004_),
    .D(_007_[6]),
    .Q(program_up_reg[6]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:49|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _106_ (
    .C(_002_),
    .CE(_004_),
    .D(_007_[7]),
    .Q(program_up_reg[7]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:49|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _107_ (
    .C(_002_),
    .CE(_004_),
    .D(_007_[8]),
    .Q(program_up_reg[8]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:49|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _108_ (
    .C(_002_),
    .CE(_004_),
    .D(_007_[9]),
    .Q(program_up_reg[9]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:49|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _109_ (
    .C(_002_),
    .CE(_004_),
    .D(_007_[10]),
    .Q(program_up_reg[10]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:49|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _110_ (
    .C(_002_),
    .CE(_004_),
    .D(_007_[11]),
    .Q(program_up_reg[11]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:49|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _111_ (
    .C(_002_),
    .CE(_004_),
    .D(_007_[12]),
    .Q(program_up_reg[12]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:49|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _112_ (
    .C(_002_),
    .CE(_004_),
    .D(_007_[13]),
    .Q(program_up_reg[13]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:49|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _113_ (
    .C(_002_),
    .CE(_004_),
    .D(_007_[14]),
    .Q(program_up_reg[14]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/stefan/Projects/bitgrid-ideas/./hw.py:49|/opt/homebrew/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'h0)
  ) _114_ (
    .C(_002_),
    .CE(_004_),
    .D(_007_[15]),
    .Q(program_up_reg[15]),
    .R(_000_)
  );
  (* keep = 32'd1 *)
  IBUF _115_ (
    .I(clk),
    .O(_009_)
  );
  (* keep = 32'd1 *)
  IBUF _116_ (
    .I(in_down),
    .O(in_concat[1])
  );
  (* keep = 32'd1 *)
  IBUF _117_ (
    .I(in_left),
    .O(in_concat[2])
  );
  (* keep = 32'd1 *)
  IBUF _118_ (
    .I(in_right),
    .O(in_concat[3])
  );
  (* keep = 32'd1 *)
  IBUF _119_ (
    .I(in_up),
    .O(in_concat[0])
  );
  (* keep = 32'd1 *)
  OBUF _120_ (
    .I(out_reg[1]),
    .O(out_down)
  );
  (* keep = 32'd1 *)
  OBUF _121_ (
    .I(out_reg[2]),
    .O(out_left)
  );
  (* keep = 32'd1 *)
  OBUF _122_ (
    .I(out_reg[3]),
    .O(out_right)
  );
  (* keep = 32'd1 *)
  OBUF _123_ (
    .I(out_reg[0]),
    .O(out_up)
  );
  (* keep = 32'd1 *)
  IBUF _124_ (
    .I(program_down[0]),
    .O(_003_[0])
  );
  (* keep = 32'd1 *)
  IBUF _125_ (
    .I(program_down[1]),
    .O(_003_[1])
  );
  (* keep = 32'd1 *)
  IBUF _126_ (
    .I(program_down[10]),
    .O(_003_[10])
  );
  (* keep = 32'd1 *)
  IBUF _127_ (
    .I(program_down[11]),
    .O(_003_[11])
  );
  (* keep = 32'd1 *)
  IBUF _128_ (
    .I(program_down[12]),
    .O(_003_[12])
  );
  (* keep = 32'd1 *)
  IBUF _129_ (
    .I(program_down[13]),
    .O(_003_[13])
  );
  (* keep = 32'd1 *)
  IBUF _130_ (
    .I(program_down[14]),
    .O(_003_[14])
  );
  (* keep = 32'd1 *)
  IBUF _131_ (
    .I(program_down[15]),
    .O(_003_[15])
  );
  (* keep = 32'd1 *)
  IBUF _132_ (
    .I(program_down[2]),
    .O(_003_[2])
  );
  (* keep = 32'd1 *)
  IBUF _133_ (
    .I(program_down[3]),
    .O(_003_[3])
  );
  (* keep = 32'd1 *)
  IBUF _134_ (
    .I(program_down[4]),
    .O(_003_[4])
  );
  (* keep = 32'd1 *)
  IBUF _135_ (
    .I(program_down[5]),
    .O(_003_[5])
  );
  (* keep = 32'd1 *)
  IBUF _136_ (
    .I(program_down[6]),
    .O(_003_[6])
  );
  (* keep = 32'd1 *)
  IBUF _137_ (
    .I(program_down[7]),
    .O(_003_[7])
  );
  (* keep = 32'd1 *)
  IBUF _138_ (
    .I(program_down[8]),
    .O(_003_[8])
  );
  (* keep = 32'd1 *)
  IBUF _139_ (
    .I(program_down[9]),
    .O(_003_[9])
  );
  (* keep = 32'd1 *)
  IBUF _140_ (
    .I(program_enable),
    .O(_004_)
  );
  (* keep = 32'd1 *)
  IBUF _141_ (
    .I(program_left[0]),
    .O(_005_[0])
  );
  (* keep = 32'd1 *)
  IBUF _142_ (
    .I(program_left[1]),
    .O(_005_[1])
  );
  (* keep = 32'd1 *)
  IBUF _143_ (
    .I(program_left[10]),
    .O(_005_[10])
  );
  (* keep = 32'd1 *)
  IBUF _144_ (
    .I(program_left[11]),
    .O(_005_[11])
  );
  (* keep = 32'd1 *)
  IBUF _145_ (
    .I(program_left[12]),
    .O(_005_[12])
  );
  (* keep = 32'd1 *)
  IBUF _146_ (
    .I(program_left[13]),
    .O(_005_[13])
  );
  (* keep = 32'd1 *)
  IBUF _147_ (
    .I(program_left[14]),
    .O(_005_[14])
  );
  (* keep = 32'd1 *)
  IBUF _148_ (
    .I(program_left[15]),
    .O(_005_[15])
  );
  (* keep = 32'd1 *)
  IBUF _149_ (
    .I(program_left[2]),
    .O(_005_[2])
  );
  (* keep = 32'd1 *)
  IBUF _150_ (
    .I(program_left[3]),
    .O(_005_[3])
  );
  (* keep = 32'd1 *)
  IBUF _151_ (
    .I(program_left[4]),
    .O(_005_[4])
  );
  (* keep = 32'd1 *)
  IBUF _152_ (
    .I(program_left[5]),
    .O(_005_[5])
  );
  (* keep = 32'd1 *)
  IBUF _153_ (
    .I(program_left[6]),
    .O(_005_[6])
  );
  (* keep = 32'd1 *)
  IBUF _154_ (
    .I(program_left[7]),
    .O(_005_[7])
  );
  (* keep = 32'd1 *)
  IBUF _155_ (
    .I(program_left[8]),
    .O(_005_[8])
  );
  (* keep = 32'd1 *)
  IBUF _156_ (
    .I(program_left[9]),
    .O(_005_[9])
  );
  (* keep = 32'd1 *)
  IBUF _157_ (
    .I(program_right[0]),
    .O(_006_[0])
  );
  (* keep = 32'd1 *)
  IBUF _158_ (
    .I(program_right[1]),
    .O(_006_[1])
  );
  (* keep = 32'd1 *)
  IBUF _159_ (
    .I(program_right[10]),
    .O(_006_[10])
  );
  (* keep = 32'd1 *)
  IBUF _160_ (
    .I(program_right[11]),
    .O(_006_[11])
  );
  (* keep = 32'd1 *)
  IBUF _161_ (
    .I(program_right[12]),
    .O(_006_[12])
  );
  (* keep = 32'd1 *)
  IBUF _162_ (
    .I(program_right[13]),
    .O(_006_[13])
  );
  (* keep = 32'd1 *)
  IBUF _163_ (
    .I(program_right[14]),
    .O(_006_[14])
  );
  (* keep = 32'd1 *)
  IBUF _164_ (
    .I(program_right[15]),
    .O(_006_[15])
  );
  (* keep = 32'd1 *)
  IBUF _165_ (
    .I(program_right[2]),
    .O(_006_[2])
  );
  (* keep = 32'd1 *)
  IBUF _166_ (
    .I(program_right[3]),
    .O(_006_[3])
  );
  (* keep = 32'd1 *)
  IBUF _167_ (
    .I(program_right[4]),
    .O(_006_[4])
  );
  (* keep = 32'd1 *)
  IBUF _168_ (
    .I(program_right[5]),
    .O(_006_[5])
  );
  (* keep = 32'd1 *)
  IBUF _169_ (
    .I(program_right[6]),
    .O(_006_[6])
  );
  (* keep = 32'd1 *)
  IBUF _170_ (
    .I(program_right[7]),
    .O(_006_[7])
  );
  (* keep = 32'd1 *)
  IBUF _171_ (
    .I(program_right[8]),
    .O(_006_[8])
  );
  (* keep = 32'd1 *)
  IBUF _172_ (
    .I(program_right[9]),
    .O(_006_[9])
  );
  (* keep = 32'd1 *)
  IBUF _173_ (
    .I(program_rst),
    .O(_019_[0])
  );
  (* keep = 32'd1 *)
  IBUF _174_ (
    .I(program_up[0]),
    .O(_007_[0])
  );
  (* keep = 32'd1 *)
  IBUF _175_ (
    .I(program_up[1]),
    .O(_007_[1])
  );
  (* keep = 32'd1 *)
  IBUF _176_ (
    .I(program_up[10]),
    .O(_007_[10])
  );
  (* keep = 32'd1 *)
  IBUF _177_ (
    .I(program_up[11]),
    .O(_007_[11])
  );
  (* keep = 32'd1 *)
  IBUF _178_ (
    .I(program_up[12]),
    .O(_007_[12])
  );
  (* keep = 32'd1 *)
  IBUF _179_ (
    .I(program_up[13]),
    .O(_007_[13])
  );
  (* keep = 32'd1 *)
  IBUF _180_ (
    .I(program_up[14]),
    .O(_007_[14])
  );
  (* keep = 32'd1 *)
  IBUF _181_ (
    .I(program_up[15]),
    .O(_007_[15])
  );
  (* keep = 32'd1 *)
  IBUF _182_ (
    .I(program_up[2]),
    .O(_007_[2])
  );
  (* keep = 32'd1 *)
  IBUF _183_ (
    .I(program_up[3]),
    .O(_007_[3])
  );
  (* keep = 32'd1 *)
  IBUF _184_ (
    .I(program_up[4]),
    .O(_007_[4])
  );
  (* keep = 32'd1 *)
  IBUF _185_ (
    .I(program_up[5]),
    .O(_007_[5])
  );
  (* keep = 32'd1 *)
  IBUF _186_ (
    .I(program_up[6]),
    .O(_007_[6])
  );
  (* keep = 32'd1 *)
  IBUF _187_ (
    .I(program_up[7]),
    .O(_007_[7])
  );
  (* keep = 32'd1 *)
  IBUF _188_ (
    .I(program_up[8]),
    .O(_007_[8])
  );
  (* keep = 32'd1 *)
  IBUF _189_ (
    .I(program_up[9]),
    .O(_007_[9])
  );
  (* keep = 32'd1 *)
  IBUF _190_ (
    .I(rst),
    .O(_018_[0])
  );
  (* keep = 32'd1 *)
  IBUF _191_ (
    .I(run_enable),
    .O(_008_)
  );
  (* keep = 32'd1 *)
  IBUF _192_ (
    .I(run_rst),
    .O(_018_[1])
  );
  assign _011_[1:0] = { in_concat[2], in_concat[3] };
  assign _013_[1:0] = { in_concat[2], in_concat[3] };
  assign _010_[0] = in_concat[1];
  assign _016_[0] = in_concat[1];
  assign _014_[0] = in_concat[1];
  assign _017_[1:0] = { in_concat[2], in_concat[3] };
  assign _012_[0] = in_concat[1];
  assign _015_[1:0] = { in_concat[2], in_concat[3] };
  assign _019_[1] = _018_[0];
  assign \$auto$verilog_backend.cc:2352:dump_module$1  = 1'h0;
endmodule
